// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchUploadFile() {
  return window['go']['backend']['App']['BatchUploadFile']();
}

export function CheckFile(arg1) {
  return window['go']['backend']['App']['CheckFile'](arg1);
}

export function CopyFileUrl(arg1) {
  return window['go']['backend']['App']['CopyFileUrl'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['backend']['App']['DeleteFile'](arg1);
}

export function GetConfig() {
  return window['go']['backend']['App']['GetConfig']();
}

export function GetList() {
  return window['go']['backend']['App']['GetList']();
}

export function Menu() {
  return window['go']['backend']['App']['Menu']();
}

export function SetConfig(arg1) {
  return window['go']['backend']['App']['SetConfig'](arg1);
}

export function SyncDatabase() {
  return window['go']['backend']['App']['SyncDatabase']();
}

export function UpdateFileName(arg1, arg2) {
  return window['go']['backend']['App']['UpdateFileName'](arg1, arg2);
}

export function Upload(arg1, arg2) {
  return window['go']['backend']['App']['Upload'](arg1, arg2);
}
